services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: express-app

    depends_on:
      mongodb:
        condition: service_healthy
        required: true

    environment:
      MONGO_URI: mongodb://mongodb:27017/dockerdb
      PORT: "3000"

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:8

    container_name: mongodb

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
